name: training-data-prep
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
    - azureml-sdk
    - azureml-mlflow==1.38.0
    - pandas
    - scikit-learn

    # - azure-identity==1.7.1 
    # - azure-common==1.1.28