$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: active_learning_cv_pipeline
experiment_name: active_learning_cv_pipeline
jobs:
  prep-job:
    type: command
    code: 
      local_path: ../data_engineering
    command: >-
      python training_data_prep.py 
      --target_path ${{inputs.target_path}}
      --datastore ${{inputs.datastore}}
      --ds_prefix ${{inputs.ds_prefix}}
    inputs:
      target_path: "MIT_Indoor/aml_annotations" #the folder in the datastore to store the name of the jsol data file. File name will be unique
      datastore: "mltraining"
      ds_prefix: "img_active_learning"
    environment:
      conda_file: ../data_engineering/conda_training_data_prep.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
    compute: azureml:d12-v2-ssh
    description: Creating net AML dataset for training from labelled dataset
  
  train-job:
    type: command
    code: 
      local_path: ../training
    command: >-
      python cv_automl_train.py 
      --compute_cluster ${{inputs.compute_cluster}}
      --training_dataset ${{inputs.training_dataset}}
      --validation_dataset ${{inputs.validation_dataset}}
      --experiment_name ${{inputs.experiment_name}}
      --model_name ${{inputs.model_name}}
    inputs:
      compute_cluster: "gpunc6"
      training_dataset: "train_img_active_learning"
      validation_dataset: "val_img_active_learning"
      experiment_name: 'automl-image-multiclass-label'
      model_name: 'ActiveLearningCV_Label_Model'
    environment:
      conda_file: ../training/conda_cv_automl_train.yml
      image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
    compute: azureml:d12-v2-ssh

    description: Run CV-AutoML train
      





# $schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
# type: pipeline

# description: "pipeline to prep and train data"
# inputs:
#   training_dataset: "train_img_active_learning"
#   validation_dataset: "val_img_active_learning"
# compute: azureml:d12-ssh-novnet

# jobs:  
#   dataprep-job:
#     type: component
#     component: file:./training_data_prep.yml
#   train-job:
#     type: component
#     component: file:./cv_automl_train.yml
#     inputs:
#       training_dataset: ${{inputs.training_dataset}}
#       validation_dataset: ${{inputs.validation_dataset}}