name: mlops-workshop-local
channels:
  - conda-forge

dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
    - azureml-sdk
    - azureml-mlflow==1.38.0
    - azureml-opendatasets
    - pandas
    - scikit-learn