name: data-selection
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.3.1
  - pip:
    - azure-kusto-data==3.0.1 
    - azureml-defaults==1.38.0
    - azureml-mlflow==1.38.0
    - pandas

    # - azure-identity==1.7.1 
    # - azure-common==1.1.28