$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: 
  local_path: ./
command: >-
  python training_data_prep.py 
  --target_path ${{inputs.target_path}}
  --datastore ${{inputs.datastore}}
  --ds_prefix ${{inputs.ds_prefix}}
inputs:
  target_path: "MIT_Indoor/aml_annotations" #the folder in the datastore to store the name of the jsol data file. File name will be unique
  datastore: "mltraining"
  ds_prefix: "img_active_learning"
environment:
  conda_file: ./conda_training_data_prep.yml
  image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04:latest
compute: azureml:d12-v2-ssh
display_name: raining-data-prep
experiment_name: training-data-prep
description: Creating net AML dataset for training from labelled dataset
