name: unit_test
on:
  workflow_dispatch:
  # add additional trigger

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine
      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: $${{ secrets.JAMES_AZURE_CREDENTIALS }} # change to point to your GitHub Secret Name
      - name: Run Feature Engineering
        uses: ./.github/actions/aml-job-create
        with:
          jobFile: src/workshop/core/data_engineering/feature_engineering.yml