name: workshop-cd
on:
  workflow_dispatch:
  push:
    branches: 
    - aldelar-dev
    paths:
      - src/workshop/core/**
      - .github/workflows/workshop_cd.yml
      - .github/actions/**
  # workflow_run:
  #   workflows: [workshop-ci]
  #   branches: [integration]
  #   types:
  #     - completed
  # push:
  #   branches: 
  #   - james-dev
  #   paths:
  #     - src/workshop/core/scoring/*
  #     - .github/workflows/workshop_cd.yml
jobs:
  
  deployment:
    runs-on: ubuntu-latest
    steps:

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' # Version range or exact version of a Python version to use, using SemVer's version range syntax 

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build
          python -m pip install --upgrade twine

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_ALDELAR }}

      - name: Install az ml & and tools
        run: |
          az extension add -n ml -y
          sudo apt install jq
          pip install yq
      
      - name: Run deployment
        uses: ./.github/actions/aml-endpoint-deploy
        with:
          endpointFile: src/workshop/core/scoring/endpoint.yml
          deploymentFile: realtime_score.yml
          workspaceName: mlops-workshop
          resourceGroup: mlops-workshop
          keyVaultName: mlopsworkshop833930030
          modelVersion: latest
      
      - name: Test deployment
        uses: ./.github/actions/aml-endpoint-test
        with:
          endpointFile: src/workshop/core/scoring/endpoint.yml
          workspaceName: mlops-workshop
          resourceGroup: mlops-workshop
          keyVaultName: mlopsworkshop833930030

      - name: Swap deployment
        uses: ./.github/actions/aml-endpoint-swap
        with:
          endpointFile: src/workshop/core/scoring/endpoint.yml
          workspaceName: mlopsworkshop833930030
          resourceGroup: mlops-workshop